# Generated by Django 4.0.4 on 2022-05-28 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('ranking', models.IntegerField(choices=[(3, '3 estrelas'), (2, '2 estrelas'), (4, '4 estrelas'), (5, '5 estrelas'), (1, '1 estrela')])),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('instituicao', models.CharField(max_length=50)),
                ('ano_inicio', models.IntegerField()),
                ('ano_fim', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano_inicio', models.IntegerField()),
                ('ano_fim', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habilitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30)),
                ('data', models.DateField(auto_now_add=True)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('lusofona', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True, max_length=500)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('ano_realizado', models.IntegerField(default=0)),
                ('github', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('tech_usado', models.TextField(default='none')),
                ('cadeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadeira', to='portfolio.cadeira')),
                ('participantes', models.ManyToManyField(blank=True, related_name='participacao', to='portfolio.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docente_praticas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praticas', to='portfolio.professor'),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docente_teorica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor'),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='linguagens',
            field=models.ManyToManyField(blank=True, to='portfolio.linguagem'),
        ),
    ]
