# Generated by Django 4.0.4 on 2022-05-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_cadeira_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='ranking',
            field=models.IntegerField(choices=[(5, '5 estrelas'), (1, '1 estrela'), (4, '4 estrelas'), (2, '2 estrelas'), (3, '3 estrelas')]),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
    ]
