# Generated by Django 4.0.4 on 2022-05-31 11:21

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_cadeira_ranking_alter_projeto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='extensao',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ranking',
            field=models.IntegerField(choices=[(5, '5 estrelas'), (2, '2 estrelas'), (1, '1 estrela'), (3, '3 estrelas'), (4, '4 estrelas')]),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=portfolio.models.projeto_path),
        ),
    ]
