# Generated by Django 4.0.4 on 2022-06-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_tecnica_alter_cadeira_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='ranking',
            field=models.IntegerField(choices=[(3, '3 estrelas'), (1, '1 estrela'), (5, '5 estrelas'), (4, '4 estrelas'), (2, '2 estrelas')]),
        ),
    ]
