# Generated by Django 4.0.4 on 2022-06-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_pontuacaoquizz_alter_cadeira_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontuacaoquizz',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ranking',
            field=models.IntegerField(choices=[(4, '4 estrelas'), (3, '3 estrelas'), (5, '5 estrelas'), (1, '1 estrela'), (2, '2 estrelas')]),
        ),
    ]
