# Generated by Django 4.0.4 on 2022-06-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_tecnologia_alter_cadeira_ranking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='ranking',
            field=models.IntegerField(choices=[(2, '2 estrelas'), (3, '3 estrelas'), (5, '5 estrelas'), (4, '4 estrelas'), (1, '1 estrela')]),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tech_usado',
            field=models.TextField(blank=True, default='none'),
        ),
    ]
