# Generated by Django 4.0.4 on 2022-06-12 02:38

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_cadeira_ranking_remove_projeto_tech_usado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='ranking',
            field=models.IntegerField(choices=[(5, '5 estrelas'), (4, '4 estrelas'), (1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas')]),
        ),
        migrations.CreateModel(
            name='Tfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
                ('imagem', models.ImageField(blank=True, upload_to=portfolio.models.projeto_path)),
                ('relatorio', models.FileField(blank=True, upload_to='')),
                ('link_github', models.CharField(blank=True, max_length=150)),
                ('link_video', models.CharField(blank=True, max_length=150)),
                ('autores', models.ManyToManyField(related_name='tfcAutores', to='portfolio.pessoa')),
                ('orientadores', models.ManyToManyField(related_name='tfcOrientadores', to='portfolio.professor')),
            ],
        ),
    ]
