# Generated by Django 4.0.4 on 2022-06-12 14:16

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_cadeira_ranking_tfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='ranking',
            field=models.IntegerField(choices=[(2, '2 estrelas'), (1, '1 estrela'), (3, '3 estrelas'), (5, '5 estrelas'), (4, '4 estrelas')]),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=portfolio.models.tfcs_path),
        ),
    ]
