# Generated by Django 4.0.5 on 2022-06-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_cadeira_ranking_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='ranking',
            field=models.IntegerField(choices=[(3, '3 estrelas'), (5, '5 estrelas'), (2, '2 estrelas'), (1, '1 estrela'), (4, '4 estrelas')]),
        ),
    ]
